### ISSUE TITLE
RTDB transaction (ref.update) do not work as expected

### ISSUE THREAD

**Issue by huafu** [soumak77/firebase-mock#94]
Consider this as database:
```yml
tests:
  id1:
    foo: 1
```

Normally if you run the following update:
```js
db.ref().update({ 'tests/id1': { bar: 2 } })
```
You should get this as the database state:
```yml
tests:
  id1:
    bar: 2
```
but here is what you get instead with `firebase-mock`:
```yml
tests:
  id1:
    foo: 1
    bar: 2
```

Update should act as a multi `set`, overriding the value at the location(s) pointed by each the given object's key.

_I'll try to provide a PR fixing this ASAP..._
